### ISSUE TITLE
Inference code do not work

### ISSUE THREAD

**Issue by sawyer7246** [DavidGillsjo/polygon-HGT#3]
pls. help
```python
(base) root@d4cdadf5a082:/home/project/polygon-HGT/scripts# python3 test.py --config-file ../config-files/Pred-simple-plane-S3D-GNN.yaml  --img-folder ../test_data/ CHECKPOINT ../data/model_polygon_hgt_joint.pth
2023-07-15 14:56:15,695 srw-test INFO: Namespace(config_file='../config-files/Pred-simple-plane-S3D-GNN.yaml', nbr_plots=5, img_folder='../test_data/', filenames=None, all=False, subsample=1, val=False, graph=False, disable_wandb=False, resume_wandb=False, skip_tb=False, write_latex=False, no_legend=False, opts=['CHECKPOINT', '../data/model_polygon_hgt_joint.pth'])
2023-07-15 14:56:15,696 srw-test INFO: Loaded configuration file ../config-files/Pred-simple-plane-S3D-GNN.yaml
Traceback (most recent call last):
  File "/home/project/polygon-HGT/scripts/test.py", line 964, in <module>
    test(0, *test_args)
  File "/home/project/polygon-HGT/scripts/test.py", line 855, in test
    tester = ModelTester(cfg,
  File "/home/project/polygon-HGT/scripts/test.py", line 67, in __init__
    self.datasets = build_test_dataset(cfg, validation = validation)
  File "/home/project/polygon-HGT/scripts/../parsing/dataset/build.py", line 78, in build_test_dataset
    dataset = factory(**args)
  File "/home/project/polygon-HGT/scripts/../parsing/dataset/test_dataset.py", line 24, in __init__
    with open(ann_file, 'r') as _:
FileNotFoundError: [Errno 2] No such file or directory: '/home/project/polygon-HGT/data/Structured3D_wf/test.json'
Segmentation fault (core dumped)
```

**Comment by DavidGillsjo** [comment]
Thanks for reporting this, I'll have a look.

**Comment by khushaljethava** [comment]
any luck on this? I am facing the same issue.

**Comment by DavidGillsjo** [comment]
I'm currently short on time so I apologize that this is taking a long time to fix.
I currently have two branches:

`inference_issues` which use a new cuspatial version and has ported some parts of the code to make it work. It should also have resolved any inference issues. I have not  finished verifying the performance, it seems like the old weights perform badly and I don't get why.

`old_docker_version` tries to replicate the old docker environment including cuspatial version. If I get this working and try on the weights I can deduce if the issue is with the weights or the new cuspatial version.

**Comment by khushaljethava** [comment]
Do you have any idea how I can get four corners of the floor from Room Layout?
