### ISSUE TITLE
Failed to run test.py

### ISSUE THREAD

**Issue by 1372746244** [DavidGillsjo/polygon-HGT#4]
pls. help
when I was running test. py, the following error occurred
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/polygon-HGT/./test.py", line 961, in <module>
    test(0, *test_args)
  File "/content/drive/MyDrive/polygon-HGT/./test.py", line 863, in test
    tester.test_model_on_folder(args.img_folder)
  File "/content/drive/MyDrive/polygon-HGT/./test.py", line 703, in test_model_on_folder
    output, extra_info = model(image_tensor[None].to(self.device), [ann])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/polygon-HGT/parsing/detector.py", line 94, in forward
    return self.forward_test(images, annotations=annotations, output_features=output_features)
  File "/content/drive/MyDrive/polygon-HGT/parsing/detector.py", line 163, in forward_test
    output_planes, extra_info_planes = self.plane_classifier.forward_test(juncs_final, output_lines, features, img=images[0])
  File "/content/drive/MyDrive/polygon-HGT/parsing/modules/plane_detection_gnn.py", line 628, in forward_test
    inf_output = self._inference(
  File "/content/drive/MyDrive/polygon-HGT/parsing/modules/plane_detection_gnn.py", line 479, in _inference
    sampled_polygon_features, plane_masks, polygon_centroids = self._sample_polygon_feature(plane_polygon_features, hyp_planes_pos)
  File "/content/drive/MyDrive/polygon-HGT/parsing/modules/plane_detection.py", line 350, in _sample_polygon_feature
    plane_masks = self.eval.polygons2masks(plane_pos)
  File "/content/drive/MyDrive/polygon-HGT/parsing/utils/plane_evaluation.py", line 186, in polygons2masks
    mask_frame = cs.point_in_polygon(self.points_x,self.points_y, **poly_dict)
TypeError: point_in_polygon() got an unexpected keyword argument 'poly_points_x'
```

**Comment by stansf** [comment]
Faced the same error. Have you found a solution?
